#ifndef TEXTFACTORY_GLOBAL_H
#define TEXTFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTFACTORY_LIBRARY)
#  define TEXTFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTFACTORY_GLOBAL_H
