#ifndef IMAGEFACTORY_GLOBAL_H
#define IMAGEFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEFACTORY_LIBRARY)
#  define IMAGEFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEFACTORY_GLOBAL_H
