#ifndef THEMEIMPLEMENTATION2_GLOBAL_H
#define THEMEIMPLEMENTATION2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THEMEIMPLEMENTATION2_LIBRARY)
#  define THEMEIMPLEMENTATION2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define THEMEIMPLEMENTATION2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THEMEIMPLEMENTATION2_GLOBAL_H
