#ifndef THEMEIMPLEMENTATION_GLOBAL_H
#define THEMEIMPLEMENTATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THEMEIMPLEMENTATION_LIBRARY)
#  define THEMEIMPLEMENTATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THEMEIMPLEMENTATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THEMEIMPLEMENTATION_GLOBAL_H
